### PR TITLE
Use flexvolume information to populate job listing

### LINKED ISSUE #355: When input and output datasets are re-used the job listing stacks the outputs and inputs
## Expected Behavior
```
JOB       IMAGE                       INPUT                                     OUTPUT                                        MEMORY   VCPU   CREATED AT      PHASE      DETAILS             
d3d-run   quay.io/nerdalize/delft3d   d3d-input   d3d-output   0.2      0.2    2 seconds ago   Starting   ContainerCreating 
```

## Actual Behavior
```
JOB       IMAGE                       INPUT                                     OUTPUT                                        MEMORY   VCPU   CREATED AT      PHASE      DETAILS             
d3d-run   quay.io/nerdalize/delft3d   d3d-input,d3d-input,d3d-input,d3d-input   d3d-output,d3d-output,d3d-output,d3d-output   0.2      0.2    2 seconds ago   Starting   ContainerCreating 
```

## Steps to Reproduce the Problem

  1. re-use one dataset in multiple jobs
  1. delete old jobs

### PR DESCRIPTION
**Pull request by LilliJane**
Closes #355 

Before we were listing the datasets and then mapping the jobs and the datasets together. As the datasets contain a list of jobs that used them, if someone would name a job as a deleted job, this person would see in the job listing many datasets even if this job isn't using any dataset.

Now we use the job's specs: in the flex volume options we can find the `input/dataset` and `output/dataset`. This also removes one step, we don't have to list all the datasets to get a proper list of jobs.

### CODE REVIEW

File: svc/kube_list_jobs.go [hunk 1]
```diff
@@ -145,14 +135,15 @@ func (k *Kube) ListJobs(ctx context.Context, in *ListJobsInput) (out *ListJobsOu
...
-		if ok {
-			item.Input = d
-		}
-
-		d, ok = outputs[job.Name]
-		if ok {
-			item.Output = d
+		for _, dataset := range job.Spec.Template.Spec.Volumes {
+			if dataset.FlexVolume != nil {
+				if dataset.FlexVolume.Options["input/dataset"] != "" {
```
Comment (advanderveer) [inline svc/kube_list_jobs.go]: Hey could you change this to the form in which it won't cause a panic if the option doesn't exist? I see this going wrong in the future when the options map changes around. So like:

```
if _, ok :=  dataset.FlexVolume.Options["input/dataset"]; ok {

}
```

Comment (advanderveer) [reply svc/kube_list_jobs.go]: Ok, after running this https://play.golang.org/p/8B0qyBUn5uD it seems that this won't panic. I don't know why I though this. So nvm, it can be merged
