### PR TITLE
Remove project naming

### LINKED ISSUE #312: Remove all 'project' references in messages and feedback
It is sometimes still possible to get the feedback that you need to set a project with 'nerd project set', this is possibly triggered by not being logged in but the error message is confusing:

```
matesitox@matesitox-omega:~$ nerd job list
error: No project ID specified, use `nerd project set` to configure a project to work on.
(but there is no nerd project set in the help) MDM
also with `nerd dataset list`
also with `nerd job list`
and with all other commands1
```

### LINKED ISSUE #325: Remove cluster configuration from the kube config file if connecting fails
If the login fails it shoeldn't create a kubeconfig file so when another command is run it gives the user correct feedback about loggin in first.

### PR DESCRIPTION
**Pull request by LilliJane**
* Fixes #312 and #313 by removing "project" from the cli output and by providing better feedback
* Fixes #325 by removing config from kube config file if there is a problem when we set a project/cluster

### CODE REVIEW

File: command/login.go [hunk 1]
```diff
@@ -97,22 +97,21 @@ func (cmd *Login) DoRun(args []string) error {
...
 		if err != nil {
-			cmd.ui.Info(fmt.Sprintf("Could not set project %s, trying with another one. Error: %v", projectSlug, err))
 			projectSlug = ""
 			continue
 		}
 		break
 	}
 	if projectSlug == "" {
-		cmd.ui.Info("Successful login. You can now list your projects using 'nerd project list'.")
+		cmd.ui.Info("Successful login, but it seems that there is a connection problem to your cluster(s). Please try again, and if the problem persists, contact mayday@nerdalize.com.")
```
Comment (LilliJane) [inline command/login.go]: @advanderveer do you think this feedback is good enough? Isn't it a bit weird to say "successful login" and at the same time "there is a problem"?
