### PR TITLE
Fail command when too many arguments are provided,  fix #323

### LINKED ISSUE #323: Fail the command when too many arguments are given
Currently when a command is given too many argument it just takes the first. Instead we want to fail because we're running something that the user didn't intend. Exception is the `nerd job run`

### PR DESCRIPTION
**Pull request by LilliJane**

### CODE REVIEW

File: cmd/cmd.go [hunk 1]
```diff
@@ -18,6 +18,12 @@ var (
 	//MessageNotEnoughArguments is shown when the user didn't provide enough arguments
 	MessageNotEnoughArguments = "Not enough arguments, this command requires at least %d argument%s."
 
+	//MessageTooManyArguments is shown when the user provides too many arguments
+	MessageTooManyArguments = "Too may arguments, this command takes at most %d argument%s."
```
Comment (advanderveer) [inline cmd/cmd.go]: Thats cool! I never thought of that, makeshift templating
